# Solutions for known {{ dataproc-name }} issues

* [Resolving the error of access to S3 buckets from a DataProc 1.4 cluster](cannot-access-buckets.md)
* [DataProc cluster is in the Unknown state immediately after creation](hosts-of-dataproc-cluster-are-in-status-unknown-after-creation.md)